project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!posts/07_bead/proj-fcc-report/*.qmd"
    - "posts/07_bead/proj-fcc-report/index.qmd"
    - "!posts/fcc-duckdb/proj-fcc-report/*.qmd"
    - "posts/fcc-duckdb/proj-fcc-report/index.qmd"

website:
  title: "Mapping & Data Analytics Blog @cori-risi"
  search: false
  favicon: assets/images/Logo-Mark_Black.png
  open-graph: true
  google-analytics: "G-07QRVQQ5JK"
  navbar:
    logo-href: https://ruralinnovation.us/our-work/research_mapping/
    left:
      - href: index.qmd
        text: Mapping & Data Analytics Blog
    right:
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/ruralinnovation
format:
  html:
    theme:
      - minty
      - src/custom.scss
    css: assets/fonts.css
    fontcolor: "#121E22"
    linkcolor: "#00835D"
    mainfont: "Bitter"
    grid:
      sidebar-width: 250px
      body-width: 1100px
      margin-width: 250px
    toc: true

resources:
- "assets/*"

execute:
  freeze: false

