project:
  type: website
  output-dir: _site
  render:
    - "posts/**/*.qmd"

website:
  title: "Rural Dataverse"
  description: "Center on Rural Innovation - Mapping & Data Analytics"
  favicon: assets/images/Logo-Mark_Black.png
  open-graph: true
  google-analytics: "G-07QRVQQ5JK"

  navbar:
    logo: assets/images/CORI_Logo_Cream.svg
    logo-href: /
    background: "#16343E"
    foreground: white
    left:
      - text: "Home"
        href: index.html
      - text: "Datasets"
        href: posts/datasets/
      - text: "R Packages"
        href: posts/packages/
      - text: "Projects"
        href: posts/projects/
      - text: "Blog"
        href: posts/blog/
      - text: "Resources"
        href: posts/resources/
    right:
      - text: "About"
        href: about.html
      - icon: github
        href: https://github.com/ruralinnovation

  page-footer:
    background: light
    left: |
      © 2026 Center on Rural Innovation. All rights reserved.
      Your hub for rural innovation data, tools, research, and analysis.
    right:
      - text: "GitHub"
        href: https://github.com/ruralinnovation
      - text: "CORI Website"
        href: https://ruralinnovation.us

format:
  html:
    theme:
      - minty
      - src/custom.scss
    css: assets/fonts.css
    fontcolor: "#121E22"
    linkcolor: "#00835D"
    mainfont: "Bitter"
    grid:
      sidebar-width: 250px
      body-width: 1100px
      margin-width: 250px
    toc: true

# Content organization
contents:
  blog:
    path: "posts/blog"
    type: blog
  datasets:
    path: "posts/datasets"
    type: catalog
  packages:
    path: "posts/packages"
    type: catalog
  projects:
    path: "posts/projects"
    type: portfolio
  resources:
    path: "posts/resources"
    type: catalog

execute:
  freeze: auto
  echo: true
  warning: false
  message: false
