project:
  type: website
  output-dir: docs

website:
  title: "Mapping, Data, and Analytics @ CORI"
  search: false
  favicon: assets/images/Logo-Mark_Black.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ruralinnovation
format:
  html:
    theme: minty
    css: styles.scss
    mainfont: "Bitter"
    fontcolor: "#121E22"
    linkcolor: "#00835D"
    grid:
      sidebar-width: 250px
      body-width: 1100px
      margin-width: 250px
    toc: true

resources:
- "assets/*"

execute:
  freeze: auto



